import { useState, useMemo } from "react";
import {
  AlertTriangle,
  Check,
  Copy,
  Download,
  Info,
  Loader2,
  Upload,
} from "lucide-react";
import type {
  DestinationType,
  DestinationUploadState,
  FileUploadResult,
  TaskItem,
  UploadResult,
} from "../types";
import { buildFormats } from "../uploadUtils";
import { resolveCanHotlink } from "../upload/providers";
import { buildBbcodeTitle, withoutExtension } from "../utils";

/**
 * Determine which image URL to use for a post template [img] tag.
 * When canHotlink is true, directUrl is embeddable. When false (e.g. Filester),
 * directUrl is a viewer page URL, so we fall back to mediumUrl or thumbUrl.
 * If thumbUrl equals pageUrl, no real thumbnail exists, so return null.
 */
function getPostTemplateImage(
  result: UploadResult,
  canHotlink: boolean,
  isWebp: boolean,
): string | null {
  if (canHotlink) {
    // For webp thumbnails we use the directUrl to preserve animation as thumbnails
    // generated by the host usually are static
    if (isWebp) return result.directUrl;
    return result.mediumUrl ?? result.thumbUrl;
  } else {
    // directUrl is not embeddable, use medium or thumb
    // But if thumbUrl === pageUrl, no real thumbnail image exists
    if (result.thumbUrl === result.pageUrl) return null;
    return result.mediumUrl ?? result.thumbUrl;
  }
}
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface Props {
  /** All task items. */
  items: TaskItem[];
  /** Whether all uploads across all items and destinations are complete. */
  allDone: boolean;
  /** Enabled upload destinations. */
  enabledDests: { id: string; name: string; type: string }[];
  /** Done items that have outputBlob and outputName. */
  doneItems: TaskItem[];
  /** Total possible uploads (doneItems * enabledDests). */
  totalPossibleUploads: number;
  /** Completed upload count. */
  completedUploads: number;
  /** Whether there are pending uploads. */
  hasPendingUploads: boolean;
  /** True while a bulk-upload batch is in progress. */
  isUploadingAll: boolean;
  /** True while ZIP archive is being generated. */
  isZipping: boolean;
  /** Callback to upload all completed items. */
  onUploadAll: () => void;
  /** Callback to download all completed items as ZIP. */
  onDownloadAll: () => void;
}

/**
 * Collect tasks that have at least one incomplete upload destination
 * (error or deleted file results).
 * Excludes items that currently have active uploads in progress,
 * so the error popover doesn't flash during retries.
 */
function getIncompleteUploads(items: TaskItem[]): TaskItem[] {
  return items.filter((item) => {
    if (!item.uploads) return false;
    return Object.values(item.uploads).some((state) => {
      // Skip destinations with active uploads (retries in progress)
      if (
        state.fileResults?.some(
          (fr) => fr.status === "uploading" || fr.status === "idle",
        )
      ) {
        return false;
      }
      return (
        state.status === "error" ||
        state.fileResults?.some(
          (fr) => fr.status === "error" || fr.status === "deleted",
        )
      );
    });
  });
}

type FormatKey =
  | "bbcodeTitleRes"
  | "bbcodePostTemplate"
  | "bbcodeFull"
  | "bbcodeMedium"
  | "bbcodeThumb"
  | "directUrl"
  | "pageUrl"
  | "markdown"
  | "htmlImg";

const FORMAT_LABELS: Record<FormatKey, string> = {
  bbcodeTitleRes: "BBCode — video title + resolution",
  bbcodePostTemplate: "BBCode — post template",
  bbcodeFull: "BBCode — full image",
  bbcodeMedium: "BBCode — medium",
  bbcodeThumb: "BBCode — thumbnail",
  directUrl: "Direct URL",
  pageUrl: "Viewer page",
  markdown: "Markdown",
  htmlImg: "HTML img",
};

/**
 * Pick the first successful upload result for an item, across all destinations.
 * For gallery mode (fileResults), checks if any file result is done.
 *
 * @param item - The TaskItem to inspect.
 * @returns The first completed upload result, or null if none exists.
 */
function firstResult(item: TaskItem) {
  if (!item.uploads) return null;
  for (const state of Object.values(item.uploads)) {
    // Gallery mode: check if any file result is done
    // Don't require state.status === "done" — a destination can have mixed results
    // (some done, some error) which sets state.status to "error" even though
    // individual file results are complete and have valid links to copy.
    if (state.fileResults?.some((fr) => fr.status === "done")) {
      return (
        state.fileResults.find((fr) => fr.status === "done")?.result ?? null
      );
    }
    // Single upload mode: check state.result
    if (state.status === "done" && state.result) return state.result;
  }
  return null;
}

/**
 * Build the BBCode "Post Template" block for an item with multiple uploads.
 * Format: `[b]filename resolution[/b]` on the first line, then one
 * `[url=page][img]thumb[/img][/url]` per destination on the second line,
 * followed by two blank lines to separate entries.
 *
 * For providers that don't support hotlinking (canHotlink=false), if no real
 * thumbnail image is available, falls back to a plain text link instead.
 *
 * @param item - The TaskItem to build a block for.
 * @param destIdToType - Map from destination id to destination type string.
 * @returns The formatted BBCode string, or null if the item has no uploads.
 */
function buildPostBlock(
  item: TaskItem,
  destIdToType: Record<string, string>,
): string | null {
  if (!item.uploads) return null;

  const titleLine = buildBbcodeTitle(item);
  const baseName = withoutExtension(item.source.name);
  const isWebp = item.outputName?.endsWith(".webp") ?? false;

  // Collect all done file results per destination (gallery mode or single upload)
  const destLines: string[] = [];
  for (const [destId, state] of Object.entries(item.uploads)) {
    // Process any destination that has uploads attempted (don't skip error/deleted)
    const destType = (destIdToType[destId] ?? "imge") as DestinationType;
    const canHotlink = resolveCanHotlink(destType);

    // Get done file results (gallery mode) or fall back to single result
    const doneResults: FileUploadResult[] = [];
    if (state.fileResults && state.fileResults.length > 0) {
      doneResults.push(
        ...state.fileResults.filter(
          (fr) => fr.status === "done" && !!fr.result,
        ),
      );
    } else if (state.result) {
      doneResults.push({ status: "done", progress: 100, result: state.result });
    }

    if (doneResults.length === 0) continue;

    // Build image tags for all done files in this destination
    const imgTags = doneResults
      .map((fr) => {
        const result = fr.result!;
        const imageUrl = getPostTemplateImage(result, canHotlink, isWebp);
        if (imageUrl) {
          return `[url=${result.pageUrl}][img]${imageUrl}[/img][/url]`;
        } else {
          return `[url=${result.pageUrl}]${baseName}[/url]`;
        }
      })
      .join(" ");

    destLines.push(imgTags);
  }

  if (destLines.length === 0) return null;

  // Multiple destinations: each on its own line; single destination: one line
  const imgLine = destLines.join("\n");
  return `${titleLine}\n${imgLine}\n`;
}

/**
 * Collect all done file results from a destination upload state.
 * If fileResults exists (gallery mode), return done entries.
 * Otherwise fall back to the single result.
 */
function getDoneFileResults(
  state: DestinationUploadState,
): FileUploadResult[] | null {
  if (state.fileResults && state.fileResults.length > 0) {
    return state.fileResults.filter(
      (fr): fr is FileUploadResult => fr.status === "done" && !!fr.result,
    );
  }
  if (state.result) {
    return [{ status: "done", progress: 100, result: state.result }];
  }
  return null;
}

/**
 * Build the copyable text for a given format key, one line per item.
 * For "bbcodePostTemplate", items are separated by blank lines instead.
 * For gallery mode (fileResults), aggregates all frame URLs per destination
 * separated by spaces, then joins destinations with double newlines.
 *
 * @param items - The TaskItems to include (should each have at least one upload).
 * @param format - The FormatKey identifying which named link format to emit.
 * @param destIdToType - Map from destination id to destination type string.
 * @returns The combined copyable text for the selected format.
 */
function buildCopyText(
  items: TaskItem[],
  format: FormatKey,
  destIdToType: Record<string, string>,
): string {
  if (format === "bbcodeTitleRes") {
    // Title + resolution: works as long as metadata is available
    return items
      .map((item) => buildBbcodeTitle(item))
      .filter((value): value is string => Boolean(value))
      .join("\n");
  }

  if (format === "bbcodePostTemplate") {
    return items
      .map((item) => buildPostBlock(item, destIdToType))
      .filter((value): value is string => Boolean(value))
      .join("\n");
  }

  return items
    .map((item) => {
      if (!item.uploads) return null;

      const filename = item.outputName ?? item.source.name;
      const destValues: string[] = [];

      for (const [destId, state] of Object.entries(item.uploads)) {
        const doneResults = getDoneFileResults(state);
        if (!doneResults || doneResults.length === 0) continue;

        const destType = (destIdToType[destId] ?? "imge") as DestinationType;
        const canHotlink = resolveCanHotlink(destType);

        // Aggregate all file results for this destination, separated by spaces
        const fileValues = doneResults
          .map((fr) => {
            const formats = buildFormats(
              fr.result!,
              fr.filename ?? filename,
              canHotlink,
              item.metadata,
            );
            const selected = formats.find((f) => f.key === format);
            return selected?.value ?? "";
          })
          .filter(Boolean);

        if (fileValues.length > 0) {
          destValues.push(fileValues.join(" "));
        }
      }

      return destValues.length > 0 ? destValues.join("\n") : null;
    })
    .filter((value): value is string => Boolean(value))
    .join("\n\n");
}

function CopyButton({ text, disabled }: { text: string; disabled?: boolean }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (disabled || !text) return;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };

  return (
    <Button
      type="button"
      variant="default"
      size="sm"
      onClick={handleCopy}
      disabled={disabled}
      title={copied ? "Copied!" : "Copy all links"}
    >
      {copied ? (
        <>
          <Check className="size-4" /> Copied
        </>
      ) : (
        <>
          <Copy className="size-4" /> Copy All
        </>
      )}
    </Button>
  );
}

/**
 * Info popover shown when no tasks have uploaded outputs yet.
 * Explains that link-copy formats require uploads and guides users to Settings.
 * Only shows the "To get started" steps when no upload destinations are configured.
 */
function NoUploadsInfoPopover({
  hasDestinations,
}: {
  hasDestinations: boolean;
}) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className="text-muted-foreground hover:text-foreground"
          title="Link formats require uploaded outputs"
        >
          <Info className="size-4" />
        </Button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-80">
        <p className="text-sm font-medium mb-2">No uploaded outputs yet</p>
        <p className="text-sm text-muted-foreground mb-3">
          The link format options are disabled because no tasks have generated
          and uploaded outputs yet. Once you generate images/animations and
          upload them to a destination, all link formats will become available.
        </p>
        {!hasDestinations && (
          <>
            <p className="text-sm font-medium mb-1">To get started:</p>
            <ol className="text-sm text-muted-foreground list-decimal list-inside space-y-1">
              <li>
                Go to{" "}
                <span className="font-medium text-foreground">Settings</span>{" "}
                and configure and enable at least one upload destination
              </li>
              <li>Add video files and generate outputs</li>
              <li>Upload the outputs – link formats will become available</li>
            </ol>
          </>
        )}
      </PopoverContent>
    </Popover>
  );
}

/**
 * Popover that lists tasks with upload errors.
 * Shown as a warning icon next to the Copy All button so the user
 * understands why upload-dependent formats are greyed out.
 */
function ErrorPopover({ errorItems }: { errorItems: TaskItem[] }) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className="text-amber-400"
          title={`${errorItems.length} task(s) have upload errors`}
        >
          <AlertTriangle className="size-4" />
        </Button>
      </PopoverTrigger>
      <PopoverContent align="start">
        <p className="text-sm font-medium mb-2">
          These tasks have incomplete uploads (only successful uploads are
          included):
        </p>
        <ul className="list-disc list-inside space-y-1">
          {errorItems.map((item) => (
            <li
              key={item.id}
              className="text-sm text-muted-foreground break-all"
            >
              {item.source.name}
            </li>
          ))}
        </ul>
      </PopoverContent>
    </Popover>
  );
}

/**
 * Panel that groups completed-task actions: CopyAll links toolbar,
 * Upload All, and Download All buttons.
 *
 * Layout: two columns on desktop (CopyAll left, buttons right-aligned),
 * stacked on mobile.
 *
 * @param items - All task items.
 * @param allDone - True when all uploads are complete.
 * @param enabledDests - Enabled upload destinations.
 * @param doneItems - Items with outputBlob and outputName ready.
 * @param totalPossibleUploads - Max upload count across all items/destinations.
 * @param completedUploads - Number of uploads that have completed.
 * @param hasPendingUploads - True when completedUploads < totalPossibleUploads.
 * @param isUploadingAll - True while bulk-upload is in progress.
 * @param isZipping - True while ZIP archive is being generated.
 * @param onUploadAll - Starts uploading all completed items.
 * @param onDownloadAll - Downloads all completed items as ZIP.
 */
export default function TaskActionsPanel({
  items,
  enabledDests,
  doneItems,
  totalPossibleUploads,
  completedUploads,
  hasPendingUploads,
  isUploadingAll,
  isZipping,
  onUploadAll,
  onDownloadAll,
}: Props) {
  const [format, setFormat] = useState<FormatKey>("bbcodeTitleRes");

  // Only show panel if at least one item has metadata
  const analyzedItems = items.filter((i) => i.metadata);
  if (analyzedItems.length === 0) return null;

  // Only include items that have at least one upload result for upload formats.
  const uploadedItems = analyzedItems.filter((i) => firstResult(i) !== null);

  // Determine which formats are available given current state.
  // Upload formats are available as long as at least one item has a successful upload
  // (incomplete uploads on other items don't block copying the successful ones).
  const titleResAvailable = analyzedItems.length > 0;
  const uploadFormatsAvailable = uploadedItems.length > 0;
  const anyAvailable = titleResAvailable || uploadFormatsAvailable;

  // Collect items with incomplete uploads for the warning popover
  const incompleteItems = useMemo(
    () => getIncompleteUploads(analyzedItems),
    [analyzedItems],
  );

  const destIdToType: Record<string, string> = {};
  for (const d of enabledDests) {
    destIdToType[d.id] = d.type;
  }

  // Determine if any item has at least one successful upload
  const hasAnyUploads = uploadedItems.length > 0;

  const copyText = buildCopyText(analyzedItems, format, destIdToType);

  // Show panel only when there are done items or items with metadata
  const hasActions = doneItems.length > 0 || analyzedItems.length > 0;
  if (!hasActions) return null;

  return (
    <Card className="w-full overflow-hidden">
      <CardHeader>
        <CardTitle>Tasks Actions</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Column 1 - CopyAll Panel */}
          <div className="flex items-center gap-3">
            <Label className="text-sm font-medium sr-only">Copy all:</Label>
            <Select
              value={format}
              onValueChange={(v) => setFormat(v as FormatKey)}
            >
              <SelectTrigger className="w-auto min-w-1/2 **:data-[slot=select-value]:inline-block **:data-[slot=select-value]:max-w-full **:data-[slot=select-value]:truncate">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {(Object.keys(FORMAT_LABELS) as FormatKey[]).map((k) => (
                  <SelectItem
                    key={k}
                    value={k}
                    disabled={
                      k === "bbcodeTitleRes"
                        ? !titleResAvailable
                        : !uploadFormatsAvailable
                    }
                  >
                    {FORMAT_LABELS[k]}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <CopyButton text={copyText} disabled={!anyAvailable} />
            {incompleteItems.length > 0 && (
              <ErrorPopover errorItems={incompleteItems} />
            )}
            {!hasAnyUploads && (
              <NoUploadsInfoPopover hasDestinations={enabledDests.length > 0} />
            )}
          </div>

          {/* Column 2 - Action Buttons (right-aligned) */}
          <div className="flex flex-wrap items-center gap-2 justify-end">
            {enabledDests.length > 0 && doneItems.length > 0 && (
              <Button
                variant="default"
                disabled={isUploadingAll || !hasPendingUploads}
                onClick={onUploadAll}
                title={
                  hasPendingUploads
                    ? `Upload remaining files to ${enabledDests.map((d) => d.name).join(", ")}`
                    : `All ${totalPossibleUploads} upload(s) to ${enabledDests.map((d) => d.name).join(", ")} are complete`
                }
              >
                {isUploadingAll ? (
                  <>
                    <Loader2 className="size-4 animate-spin" />
                    Uploading… ({completedUploads}/{totalPossibleUploads})
                  </>
                ) : !hasPendingUploads ? (
                  <>
                    <Check className="size-4" />
                    All Uploaded
                  </>
                ) : (
                  <>
                    <Upload className="size-4" />
                    Upload All ({completedUploads}/{totalPossibleUploads})
                  </>
                )}
              </Button>
            )}
            {doneItems.length > 1 && (
              <Button
                variant="default"
                disabled={isZipping}
                onClick={onDownloadAll}
              >
                {isZipping ? (
                  <>
                    <Loader2 className="size-4 animate-spin" />
                    Zipping…
                  </>
                ) : (
                  <>
                    <Download className="size-4" />
                    Download All ({doneItems.length})
                  </>
                )}
              </Button>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
